### ISSUE TITLE
issue to better code

### ISSUE THREAD

**Issue by nftehsansarmaye** [FuelLabs/sway-farm#72]
This YAML code is for configuring the support page on GitHub. Overall, the code looks correct, but there are a few points to consider:

1. **Format of the "about" text:**
    - It is better to use a block scalar (`|`) in the "about" section instead of a folded scalar (`>`), as it improves the readability of the text.

2. **Usage of URL:**
    - The URL is repeated twice in the "about" section, which can be unnecessary. It is better to remove one of them.

3. **Link name:**
    - The link name "Need Support? Visit the Fuel Forum" might be a bit long. You can make it shorter and clearer.

With these modifications, the code would look like this:

```yaml
blank_issues_enabled: true
contact_links:
  - name: Fuel Forum Support
    url: https://forum.fuel.network
    about: |
      For support queries, please visit the Fuel Forum at https://forum.fuel.network.
      Only bug reports and feature requests in this repo are guaranteed a response.
```

These changes improve the readability and simplicity of the link.
